apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-logstash
  labels:
    component: {{ include "filebeat.fullname" . }}-logstash
data:
  access-log.conf: |
    input {
      beats {
        port => "5044"
      }
    }
    output {
      elasticsearch {
        hosts => [ "elasticsearch:9200" ]
      }
    }